
#ifndef BYZANCEPROTOCOL_H
#define BYZANCEPROTOCOL_H
 
#define BYZANCE_PROTOCOL_VERSION_1      0x01

#define BYZANCE_PROTOCOL_NO_TYPE        0x00
#define BYZANCE_PROTOCOL_BOOL_TYPE      0x01
#define BYZANCE_PROTOCOL_INT_TYPE       0x02
#define BYZANCE_PROTOCOL_FLOAT_TYPE     0x03
#define BYZANCE_PROTOCOL_STRING_TYPE    0x04

#endif /* BYZANCEPROTOCOL_H */
