#ifndef ENUM_COMPONENT_H
#define ENUM_COMPONENT_H

typedef enum {
	BIN_COMPONENT_FIRMWARE,
	BIN_COMPONENT_BOOTLOADER,
	BIN_COMPONENT_BACKUP,
	BIN_COMPONENT_BUFFER
} bin_component_t;

#endif /* ENUM_COMPONENT_H */
